MIN_AVAILABLE_ENERGY = int(os.getenv("MIN_AVAILABLE_ENERGY", 100))
SLEEP_BY_MIN_ENERGY = tuple(map(int, os.getenv("SLEEP_BY_MIN_ENERGY", "1800,3600").split(",")))
ADD_TAPS_ON_TURBO = int(os.getenv("ADD_TAPS_ON_TURBO", 2500))
AUTO_UPGRADE_TAP = os.getenv("AUTO_UPGRADE_TAP", "True") == "True"
MAX_TAP_LEVEL = int(os.getenv("MAX_TAP_LEVEL", 5))
AUTO_UPGRADE_ENERGY = os.getenv("AUTO_UPGRADE_ENERGY", "True") == "True"
MAX_ENERGY_LEVEL = int(os.getenv("MAX_ENERGY_LEVEL", 5))
AUTO_UPGRADE_CHARGE = os.getenv("AUTO_UPGRADE_CHARGE", "True") == "True"
MAX_CHARGE_LEVEL = int(os.getenv("MAX_CHARGE_LEVEL", 5))
APPLY_DAILY_ENERGY = os.getenv("APPLY_DAILY_ENERGY", "True") == "True"
APPLY_DAILY_TURBO = os.getenv("APPLY_DAILY_TURBO", "True") == "True"
RANDOM_CLICKS_COUNT = tuple(map(int, os.getenv("RANDOM_CLICKS_COUNT", "50,200").split(",")))
SLEEP_BETWEEN_TAP = tuple(map(int, os.getenv("SLEEP_BETWEEN_TAP", "10,25").split(",")))
USE_PROXY_FROM_FILE = os.getenv("USE_PROXY_FROM_FILE", "True") == "True"
USE_TAP_BOT = os.getenv("USE_TAP_BOT", "True") == "True"
EMERGENCY_STOP = os.getenv("EMERGENCY_STOP", "True") == "True"
USE_FAKE_USER_AGENT = os.getenv("USE_FAKE_USER_AGENT", "True") == "True"
USE_FAKE_IP = os.getenv("USE_FAKE_IP", "True") == "True"
SYNC_UPGRADES = os.getenv("SYNC_UPGRADES", "True") == "True"
SYNC_INTERVAL = int(os.getenv("SYNC_INTERVAL", 60))

def get_config():
    return {
        "MIN_AVAILABLE_ENERGY": MIN_AVAILABLE_ENERGY,
        "SLEEP_BY_MIN_ENERGY": SLEEP_BY_MIN_ENERGY,
        "ADD_TAPS_ON_TURBO": ADD_TAPS_ON_TURBO,
        "AUTO_UPGRADE_TAP": AUTO_UPGRADE_TAP,
        "MAX_TAP_LEVEL": MAX_TAP_LEVEL,
        "AUTO_UPGRADE_ENERGY": AUTO_UPGRADE_ENERGY,
        "MAX_ENERGY_LEVEL": MAX_ENERGY_LEVEL,
        "AUTO_UPGRADE_CHARGE": AUTO_UPGRADE_CHARGE,
        "MAX_CHARGE_LEVEL": MAX_CHARGE_LEVEL,
        "APPLY_DAILY_ENERGY": APPLY_DAILY_ENERGY,
        "APPLY_DAILY_TURBO": APPLY_DAILY_TURBO,
        "RANDOM_CLICKS_COUNT": RANDOM_CLICKS_COUNT,
        "SLEEP_BETWEEN_TAP": SLEEP_BETWEEN_TAP,
        "USE_PROXY_FROM_FILE": USE_PROXY_FROM_FILE,
        "USE_TAP_BOT": USE_TAP_BOT,
        "EMERGENCY_STOP": EMERGENCY_STOP,
        "USE_FAKE_USER_AGENT": USE_FAKE_USER_AGENT,
        "USE_FAKE_IP": USE_FAKE_IP,
        "SYNC_UPGRADES": SYNC_UPGRADES,
        "SYNC_INTERVAL": SYNC_INTERVAL,
    }